name: Resolve version
description: Read unified release version from @tutorialkit-rb/astro

outputs:
  version:
    description: 'Unified release version'
    value: ${{ steps.resolve-release-version.outputs.version }}

runs:
  using: composite

  steps:
    - name: Resolve release version
      id: resolve-release-version
      shell: bash
      run: echo "version=$(jq -r .version ./packages/astro/package.json)" >> $GITHUB_OUTPUT
